
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Disable random hash suffix
generatorOptions:
  disableNameSuffixHash: true
# namespace to deploy all Resources to
namespace: cicd
# list of Resource Config to be Applied
resources:
  - rolebinding.yaml
  - serviceaccount.yaml
secretGenerator:
- name: release-cutover-secret
  env: secrets.secret